### ISSUE TITLE
Issues with handling of --sequences and --invocations values

### ISSUE THREAD

**Issue by suvamM** [michael-emmi/violat#2]
Invoking violat with the following command

` violat --methods clear --sequences 4 --invocations 4 ./resources/specs/java/util/concurrent/ConcurrentSkipListMap.json`

returns an `Unexpected size` error. Though I can somewhat believe this- since the only alternative here is to have one invocation per thread, or at least one thread is a no-op, it may be better to have a more descriptive error message here.

Also, when I try the following:

` violat --methods clear --sequences 3 --invocations 4 ./resources/specs/java/util/concurrent/ConcurrentSkipListMap.json`

I get the following error:

`Violation or weakness discovered over 481240 executions of the following schema.
Found 0 weakness(es) and 0 violation(s).
AssertionError [ERR_ASSERTION]: 2 == 0
    at Schema.toString (/usr/lib/node_modules/violat/lib/schema.js:54:12)
    at Object.args.onResult (/usr/lib/node_modules/violat/bin/cli.js:59:27)
    at /usr/lib/node_modules/violat/lib/index.js:79:16
    at Stream.lines.on (/usr/lib/node_modules/violat/lib/jcstress.js:251:19)
    at <anonymous>`

I am not sure what the issue here is, since the value for --sequences and --invocations seem reasonable.

**Comment by michael-emmi** [comment]
Hi @suvamM, the problems you’re facing are due to an incomplete implementation of the test harness enumeration.

In principle, the enumeration should generate all possible orderings “shapes” of invocation sequences (in which some sequences are still concurrent). When there are N=2 sequences, the only satisfactory shape is that both are unordered. When there are N=3 sequences, then there are four possible shapes: (1) all unordered, (2) one before one other, and both concurrent with the third, (3) one before two others, and (4) one after two others.

The current implementation attempts (incorrectly!) to hardcode these possible shapes for N=2 and N=3. It turns out that so far we have only needed N=2 to expose violations, whose implementation trivial, and fine. If needed, N=3 should be fixed, and N>3 should be implemented.

The second error you’re seeing is also related: the printing of harness schemas to (in `Schema.toString`) has only been implemented for the simple case of N=2.

We’re happy to take a PR to address these problems should you need them.

However, I should also mention that we’ve been moving away from this *complete* enumeration of possible test programs (in `enumeration/basic.js`) towards the *random* enumeration of test programs (in `enumeration/random.js`). Our implementation of complete enumeration often explores many similar programs before getting to interesting ones. We have tried shuffling the enumeration, but this required generating all the programs eagerly, up front, before doing *any* testing. The random enumeration solved this problem, and seems to get to interesting results quickly. However, there is no guarantee that it will generate every possible test program. We have found this tradeoff to be reasonable so far.

You can use the random enumeration with the `--enum=random` flag.

Note that in the random enumeration we (so far) only generate unordered sequences. So if you really want to have ordering among sequences, we’ll have to figure that out.

**Comment by michael-emmi** [comment]
p.s. since this is very much a research prototype geared towards flexibility rather than usability, useful error messages are unfortunately not a priority :-)

**Comment by suvamM** [comment]
Thanks a lot for the clarifications Michael! That gives me much better insights into the implementation. I have just been experimenting with the tool, so I don't have any requirement for N>=3, and I see the intuition behind why you didn't need it either. 

ps: for a prototype, I actually found violat pretty usable.
